### ISSUE TITLE
Docker base image

### ISSUE THREAD

**Issue by VojtechVitek** [pressly/screenshot#1]
I noticed we're using `node:8-slim` as a base image. That's fine, and will work great.

But I wonder, if we could potentially switch to
- Alpine-based image (ie. 9.2-alpine)
- Node 9.2 (or do we have to stick with Node 8 because of Puppeteer?)

**Comment by VojtechVitek** [comment]
This is not a priority issue. The Slim-based image is good enough for sure and I guess sticking with whatever the upstream suggests makes sense too.

**Comment by MarcelRusu** [comment]
node 8 is considered more stable stable from what I've read and from the website they seem to just recommend 8 over 9. I can switch to alpine though, I'll leave this to be done after other issues

**Comment by VojtechVitek** [comment]
sounds good

> they seem to just recommend 8 over 9

pls document this in the Dockerfile, with a link to upstream

**Comment by MarcelRusu** [comment]
looks like this is still an issue, I'll leave it at 8-slim for now if that's ok then https://github.com/GoogleChrome/puppeteer/issues/379
updated Dockerfile comments
