### ISSUE TITLE
Restructure the Golang client project repo

### ISSUE THREAD

**Issue by VojtechVitek** [pressly/screenshot#4]
![screen shot 2017-12-12 at 4 53 26 pm](https://user-images.githubusercontent.com/139342/33910523-04b474c0-df5d-11e7-9c12-2ab2e8db1f83.png)

In golang, we usually put the client pkg into the top-level directory (unless the project is too big and has multiple clients, of course). Imho you can get rid of the `lib/` subdirectory :)

If you wanted to implement CLI (a terminal program that downloads screenshots from a remote server), it'd live in `/cmd/screenshot/main.go`.

When the client pkg is in the top-level directory, the imports are as easy as

```go
import (
     "github.com/pressly/screenshot"
)

func main() {
   screenshot, _ := screenshot.New(...)

   // ... 
}
```

**Comment by VojtechVitek** [comment]
In other words..
move `screenshot/main.go` to `cmd/screenshot/main.go`. Move `lib/` into the top level directory.

**Comment by VojtechVitek** [comment]
Also, try to split PNG, PDF and JPEG into separate files (ie. `client.go`, `png.go` etc.).

**Comment by MarcelRusu** [comment]
@VojtechVitek I will close this when you approve of the restructure

**Comment by VojtechVitek** [comment]
LTGM! Well done
