### ISSUE TITLE
Client.Do() to return io.Reader

### ISSUE THREAD

**Issue by VojtechVitek** [pressly/screenshot#5]
```go
	resp, body, err := c.Do(req)

	if err != nil {
		return nil, err
	}

	if resp.StatusCode != 200 {
		return nil, errors.New("Couldn't take png screenshot")
	}
	reader := bytes.NewReader(body)
```

You can pass `resp.Body` (which is io.Reader itself) down to the callers right away.

```go
resp, err := c.Do(req)

// return nil, error

// return resp.Body, nil
```

**Comment by MarcelRusu** [comment]
ah that makes sense, I'll do that

**Comment by VojtechVitek** [comment]
https://github.com/pressly/screenshot/blob/master/lib/screenshot.go#L61-L74 will return `resp.Body`

**Comment by VojtechVitek** [comment]
You might return resp (`*http.Response`) too, if you think the client should be exposed to the response headers (or any other fields) too.
