### ISSUE TITLE
Certain websites either don't load completely or load strangely

### ISSUE THREAD

**Issue by MarcelRusu** [pressly/screenshot#8]
example github, amazon, many more

somehow setting headers on puppeteer breaks things - https://github.com/pressly/screenshot/blob/master/server/src/browser.ts#L37 

will need to find a better way to forward headers

**Comment by VojtechVitek** [comment]
How does it break things?

Can you submit an upstream (GoogleChrome/puppeteer) issue? Or is it a known bug?

**Comment by MarcelRusu** [comment]
I'm still debugging, could be that I'm resetting headers or something, I'll submit an issue when I know for sure why and it's actually broken

**Comment by MarcelRusu** [comment]
Seems to just be the Host header, hardcoding a list, I think is a problem on my end not puppeteer.

**Comment by MarcelRusu** [comment]
https://github.com/pressly/screenshot/blob/master/server/src/server.ts#L260

**Comment by VojtechVitek** [comment]
Good catch :)
